[project]
name = "learnpydantic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manish Pardhan", email = "pardhanmanish7887@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[project.scripts]
learnpydantic = "learnpydantic:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
